query Diary {
  diary {
    id
    price
    status
    intervention
    interconsultation
    weight
    nextTime
    startTime
    endTime
    createdAt
    updatedAt
    service {
      id
      title
      description
    }
    patient {
      id
      dni
      name
      lastname
      phone
    }
  }
}
